### ISSUE TITLE
Make it clear if this chart is being published anywhere

### ISSUE THREAD

**Issue by WowSuchRicky** [unpoller/helm-chart#8]
Hello,

First off, thanks for the great work on this. I followed the discussion in the original Unpoller repo and found myself here. Is this chart being published anywhere? If so, can we add that URL somewhere in the documentation? As of right now it is extremely unclear out of the box how to add this helm chart and use it.

Thanks!

**Comment by jorblad** [comment]
This, I havent found it anywhere and I don't know how to add a nonpublished helm chart so I haven't been able to use it.

**Comment by jogando** [comment]
Not sure if this helps, but if you are using ArgoCD, you can point to this repo:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: unpoller
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: default
  sources:
    - repoURL:  https://github.com/unpoller/helm-chart.git
      path: charts/unpoller
      targetRevision: 2.11.2-Chart6
      helm:
        values: |
          dashboards:
            create: false
            grafana:
              create: false
          upConfig: |
            [poller]
                debug = false
                quiet = false
                plugins = []
````
